version: '3'

services:
  
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - app-network

  backend:
    depends_on:
      - mongodb
    build: backend
    ports:
      - '3001:3001'
    networks:
      - app-network

  frontend:
    depends_on:
      - backend
    build: frontend
    ports:
      - '3000:3000'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge